### verify that the /getStudentDetailsForSchool/{schoolname} endpoint is up and running
GET http://localhost:9098/getStudentDetailsForSchool/abcschool

###
GET http://localhost:8098/getSchoolDetails/abcschool

###
GET http://localhost:8098/spring-consul-client-student-service/getStudentDetailsForSchool/{schoolname}
