server:
  port: 8098

spring:
  application:
    name: spring-consul-client-school-service
  cloud:
    consul:
      host: consul.local
      port: 8500
#      discovery:
#        instance-id: consul-client-school-service-container
